language: java
install: true

jdk:
  - oraclejdk8
  - oraclejdk9

script:
  - ./gradlew --no-daemon --scan -s build publishToMavenLocal

deploy:
  - provider: script
    script: ./gradlew -s publish
    skip-cleanup: true
    on:
      branch: master
      jdk: oraclejdk8
  - provider: script
    script: ./gradlew -s publish
    skip-cleanup: true
    on:
      tags: true
      jdk: oraclejdk8
  - provider: pages
    local-dir: confij-documentation/build/asciidoc/html5
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
      jdk: oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
