= Binding
:src: ../../test/java/ch/kk7/confij/docs/Binding.java
:home: ../../test/home

The binding defines the contract of the configuration as well as the mapping
from string value to the actual configuration type.
Each configuration is organized in a tree-structure and generally immutable.

== Value Mapping

When values are read from a configuration files they are first available as Strings.
They are then transparently mapped to Objects or pimitives to match the defined type.

.Value Mapping to known types in a flat configuration
====
[source]
----
include::{src}[tag=builtinMapping]
----
[source, yaml]
----
include::{home}/mapped.yml[]
----
====
<1> mapping to primitives or java.lang objects
<2> configuration keys can be changed if the attribute name doesn't fit
<3> arrays are usually mapped from lists (see <<nested-configuration>>)
<4> or the default behavior can be changed with a custom `ValueMapping`.

=== Default Value Mapping

The default mapping behavior attempts to map from string to target type in the following order:

. if the attribute is annotated with a custom `@ValueMapper` enforce that one
  (see <<custom-value-mapping>>)
. primitives types, where `null` values are mapped to their empty types:
  a non-existent `int` becomes 0.
  booleans either have to be lowercase `true` or `false`,
  except for source languages enforcing another definition (like yaml).
. explicit mappings, for example:

  java.nio.file.Path
  java.io.File
  java.time.Duration
  java.time.Period
  ...

. all Enum-types based on the Enum's name
. classes with a static method named `valueOf(String)` or `fromString(String)`
. classes with a constructor taking a single String as input argument

TIP: Arrays/Collections are not considered leafs. In order to map a comma separated
configuration string to a `string[]` you have to annotate it with `@Separated`.

=== Built-in Value Mapping

==== Base64 encoded [[base64-mapping]]

`@Base64` expects to bind a base64-encoded string to an array or collection of bytes.

.Mapping base64 encoded configuration properties
====
[source]
----
include::{src}[tag=base64-mapping]
----
====

==== Comma Separated [[separated-mapping]]

`@Separated` expects to bind a delimited string to an array or collection of arbitrary type.


.@Separated as a short-form for collection types
====
[source]
----
include::{src}[tag=separated-mapping]
----
----
include::{home}/separated.properties[]
----
====

////
TODO
==== Time Types
==== Duration and Period
////

=== Custom Value Mapping [[custom-value-mapping]]

If the default mapping does not fit or the target type is unknown, you generally have
two options: programmatic the ConfiJBuilder or with an annotation on the affected attribute.

If a custom mapping holds for all types in the whole configuration,
it's easiest to set it in the builder when creating the configuration instance.

.Global support to map RGB codes like "#0F0F0F" to Color
====
[source]
----
include::{src}[tag=custom-value-mapping]
----
====

If a custom mapping should only be applied to specific attributes,
annotate them with `@ValueMapper(Class)`.
The mapper class must have an accessible empty constructor.

.Annotation based support to map RGB codes like "#0F0F0F" to Color
====
[source]
----
include::{src}[tag=custom-value-mapping-interface]
----
====

In order to pass compile time options to the mapper instance,
introduce fresh custom annotation, annotated with `@ValueMapper(Class)`.
See for example the implementation of <<separated-mapping>>.

== Nested Configuration [[nested-configuration]]

Configurations can themselves contain child configurations recursively.
Since every configuration is organized in a tree-structure, we call them branches.

.Simple nested configuration
====
[source]
----
include::{src}[tag=nested]
----
====

Typical branches contain, but are not limited to:

- nested interfaces (also with generics)
- Collection of interfaces, Objects (leafs), other Collections,...
- Array types of Objects, primitives, other Arrays,...
- Map types where keys are Strings and values are again anything

.Nested branches of child configurations
====
[source]
----
include::{src}[tag=nestedList]
----
[source]
----
include::{src}[tag=nestedBuild]
----
====

If the standard `Collection` interfaces are used ConfiJ will use an immutable representation of it.
But any instance can be used as long as it has an empty constructor (but at the loss of immutability).
Same holds for `Map<String,?>` types.

WARNING: Java Bean types are not supported yet. Please contribute.
