= Getting Started
:src: ../../test/java/ch/kk7/confij/docs/Setup.java
:home: ../../test/home

ConfiJ requires Java 1.8 or later.
It is modularly organized in order to reduce the amount of dependencies.
`confij-core` itself has no external dependencies.

== Repository
ConfiJ maven artifacts are available on https://search.maven.org/[Maven Central].

.Sample Gradle setup
====
[source, groovy]
[subs="verbatim,attributes"]
----
repositories {
   mavenCentral()
}
dependencies {
    implementation '{group}:confij-core:{revnumberstable}'
}
----
====

ifeval::[{revnumberstable}!={revnumber}]
The latest snapshot version `{revnumber}` will be removed after 30 days.
endif::[]

== Quick Start
.Getting started with interface configuration and ConfiJ-Builder
====
[source]
----
include::{src}[tag=simple_interface]
----
[source]
----
include::{src}[tag=simple_builder]
----
----
include::{home}/server.properties[]
----
====
<1> Define your configuration type, in this case as a Java-interface
<2> Load from various sources, in this case from a single properties file
<3> Bind the source to a configuration instance of matching type

The corresponding properties file must have the same attributes as in the interface.
ConfiJ will make sure no unknown keys are present and bind all configuration strings to their configuration types.
