= Getting Started
:src: ../../test/java/ch/kk7/confij/docs/Setup.java
:home: ../../test/home

ConfiJ requires Java 1.8 or later.
It is modularly organized in order to reduce the amount of dependencies.
`confij-core` itself has no external dependencies.

== Repository
ConfiJ maven artifacts are available on https://search.maven.org/[Maven Central].

.Sample Gradle setup
====
[source, groovy]
[subs="verbatim,attributes"]
----
repositories {
   mavenCentral()
}
dependencies {
    implementation '{group}:confij-core:{revnumberstable}:nodeps'
}
----
====

Artifacts with two different classifiers are published. The `nodeps` ones do not depend on any non-shadowed 3rd party libs and are generally prefered. The default `{group}:confij-core:{revnumberstable}` might introduce dependency issues only if an incompatible lib is already on the classpath (for example an old `com.fasterxml:classmate`).

ifeval::[{revnumberstable}!={revnumber}]
The latest snapshot version `{revnumber}` is available in the sonatype snapshot repos but will be removed after 30 days.

.Snapshot Repository
====
[source, groovy]
[subs="verbatim,attributes"]
----
repositories {
   maven {
      url 'https://oss.sonatype.org/content/repositories/snapshots/'
   }
}
dependencies {
    implementation '{group}:confij-core:{revnumber}'
}
----
====

endif::[]

== Quick Start
.Getting started with interface configuration and ConfiJ-Builder
====
[source]
----
include::{src}[tag=simple_interface]
----
[source]
----
include::{src}[tag=simple_builder]
----
----
include::{home}/server.properties[]
----
====
<1> Define your configuration type, in this case as a Java-interface
<2> Load from various sources, in this case from a single properties file
<3> Bind the source to a configuration instance of matching type

The corresponding properties file must have the same attributes as in the interface.
ConfiJ will make sure no unknown keys are present and bind all configuration strings to their configuration types.
