= Configuration Sources
:src: ../../test/java/ch/kk7/confij/docs/Source.java
:resources: ../../test/resources
:home: ../../test/home

== Source Pipelines
ConfiJ sources are loaded one after the other.
Each consecutive source overrides attributes of the previous ones.
Typically this is usefull to load a set of default values first,
then continue with application specifics and environment specific values
getting more and more detailed.
Source types can be freely mixed:

[source]
----
include::{src}[tag=interface,indent=0]

include::{src}[tag=pipedsource,indent=0]
----
<1> <<format-default,Default values>> are always loaded first (before each new source).
<2> then override with a file from the classpath root.
[source]
include::{resources}/generic.properties[]
<3> then override with a file on disk
[source]
include::{home}/server.properties[]
<4> then override with system properties prefixed by `app`
[source]
-Dapp.line=3

This will end up with the final configuration:
----
include::{resources}/pipedsource.txt[]
----

Validation generally only applies to the final configuration.
In the example above, `name` was undefined until round 3.

Variable substitution will take into account all values loaded until now.

== Supported Formats

=== Default Values [[format-default]]

Configuration default can be defined directly in your configuration interface.
For more complex scenarios where the default value is not easily stingifyable,
use a `default` method.
[source]
----
include::{src}[tag=defaults,indent=0]
----

=== YAML
[NOTE]
====
YAML format requires the `{group}.confij-yaml` maven artifact.
====

=== Properties File

=== Environment

=== System Properties

== Resource Types

=== Classpath

=== File

=== URL

== Variable Substitutions

=== built-in

=== Groovy
NOTE: Not yet implemented.
