= Configuration Sources
:src: ../../test/java/ch/kk7/confij/docs/Source.java
:resources: ../../test/resources
:home: ../../test/home

== Source Pipelines
ConfiJ loads sources one after the other.
Each consecutive source overrides (merges) attributes of the previous ones.
Typically, this is useful to load a set of default values first,
then continue with application specifics and environment specific values
getting more and more detailed.
Source types can be freely mixed, meaning you can load from classpath, then from a remote file, then from envionment variables and so on.

.Merge multiple configuration files across all formats
====
[source]
----
include::{src}[tag=interface]
----
[source]
----
include::{src}[tag=pipedsource]
----
====
<1> <<format-default,Default values>> are always loaded first.
<2> then override with a file from the classpath root.
[source]
include::{resources}/generic.properties[]
<3> then override with a file on disk (this is the first time where `name` is defined)
[source]
include::{home}/server.properties[]
<4> then override with system properties prefixed by `app`
[source]
-Dapp.line=3

This will result in the final configuration:
----
include::{resources}/pipedsource.txt[]
----

Validation generally only applies to the final configuration.
It is allowed to have incomplete configurations while there are still more configuration sources to load.

== Default Values [[format-default]]

Configuration default can be defined directly in your configuration interface using the `@Default` annotation.
For more complex scenarios where the default value is not easily stingifyable,
use a `default` method.

.Default configuration values as annotations
====
[source]
----
include::{src}[tag=defaults]
----
====

== The AnySource [[anysource]]

The `AnySource` simply takes a URI-string and determines resource location and type based on it.
It is the most compact form to specify a source unless you require special settings.

.Load from multiple sources of dynamic type and location
====
[source]
----
include::{src}[tag=anysource]
----
====

Variable substitutions are supported anywhere in the template string (see <<variables>>).
They take into account the previously loaded configuration keys.
Replacement keys are always absolute (relative to the configuration root).

Most commonly the resource location (file, classpath,...) is detected based on the URI scheme (see <<resource-locations>>).
The configuration format (yaml, json,...) is detected based on the ending.

== Sources and Formats

=== Resource Providers [[resource-locations]]

Configuration sources that can load from a file can usually load from other input streams as well.
For those, the source location and source format can be combined freely.

<<anysource>> usually detects the location based on the scheme:

- `file:` - is the default scheme and loads from the local Filesystem
- `classpath:` - load from classpath on the default classloader
- `http:` or any other registered URL format
- `git:` for GIT repositories, see <<git>>

Register custom resource providers using a <<serviceloader>> for `ch.kk7.confij.source.file.resource.ConfijResourceProvider`.

=== GIT Resource Provider [[git]]

NOTE: GIT resources require the `{group}:confij-git` maven artifact.

Configuration sources can be fetched via GIT.
For simple cases an <<anysource>> can be used with a special URL format:

- a fixed scheme 'git:'
- followed by the URI-like path to the repository.
- followed by the path to the file in the repository.
  If the repository doesn't end with `.git`, separate the filepath with two slashes `//`.
- optionally add a refspec pointing to a commit as fragment (separated from the rest by `#`).
  The default refspec is HEAD.

.Valid AnySource-URLs specifying the path to a file in a GIT-repository
====
[source,bash]
----
# annonymous https GIT repository containing /some/file.yaml
git:https://example.com/repo.git/some/file.yaml

# double slash is required if not ending with .git
git:https://example.com/repo//some/file.yaml

# BasicAuth
git:https://user:password@example.com/repo//some/file.yaml

# annonymous ssh
git:ssh://example.com/annonymous.git/some/file.yaml

# annonymous native git protocol: twice 'git' (sic)
git:git://example.com/annonymous.git/some/file.yaml

# refspec of a commit as SHA1-prefix
git:git://example.com/repo.git/file.yaml#4a4255c

# previous commit of default HEAD (usually the master branch)
git:git://example.com/repo.git/file.yaml#HEAD~1

# file on a GIT-branch named 'fuu'
git:git://example.com/repo.git/file.yaml#refs/heads/fuu

# file tagged with 'v1.0.42'
git:git://example.com/repo.git/file.yaml#refs/tags/v1.0.42
----
====

For more complex scenarios like custom SSL authentication consider extending
the existing `GitResourceProvider`.


=== YAML Format

NOTE: YAML format requires the `{group}:confij-yaml` maven artifact.

YAML is a recommended configuration source format since it maps nicely on a tree-structure.
Collection types can be represented as lists or as maps with numerical keys.

YAML can be loaded from all the <<resource-locations>>.
The `AnySource` expects a case-insensitive file ending of `.yaml` or `.yml`.

.Load from multiple sources of dynamic type and location
====
[source]
----
include::{src}[tag=yaml-interface]
----
[source,yaml]
----
include::{home}/complex.yaml[]
----
====

If the YAML source file contain multi-docs, they are loaded in order.
Internally all values are reduced to Maps of Maps or Strings.

=== HOCON/JSON Format

NOTE: HOCON format requires the `{group}:confij-hocon` maven artifact.

https://github.com/lightbend/config/blob/master/HOCON.md[HOCON] (Human-Optimized Config Object Notation)
is a format for human-readable data, and a superset of JSON and .properties.

HOCON can be loaded from all the <<resource-locations>>.
The `AnySource` expects a case-insensitive file ending of `.hocon`, `.json` or `.conf`.

The default behaviour will first perform substitutions according to the
https://github.com/lightbend/config/blob/master/HOCON.md#substitutions[HOCON Specification],
before ConfiJ's templating will kick in.

.Two substitution mechanisms
====
[source,json]
----
include::../../../../confij-hocon/src/test/resources/brefa.conf[]
----
[source,json]
----
include::../../../../confij-hocon/src/test/resources/bnotrefa.conf[]
----
====

=== Properties Format [[properties-format]]

Java properties files are part of the `{group}:confij-core` due to not having any 3rd party dependencies,
but are otherwise not recommended, since it is a flat key-value format.

Property files can be loaded from all <<resource-locations>>.
The `AnySource` expects a case-insensitive file ending of `.properties`.

.Nested configuration loading from properties file
====
[source]
----
include::{src}[tag=nestedinterface]
----
----
include::{home}/nested.properties[]
----
====

<1> Per default, nested configuration keys are separated with a dot from each other.
<2> Collection types simply require numerical keys (starting at 0).
<3> Map types can use any key excluding the delimiter.

=== Environment Variables and System Properties Format

Environment variables and system properties work similar to the file based <<properties-format>>.
System properties have to be dot separated, whereas envvars are underline separated.
To read an envvar specify a URI like `env:<prefix>`, where every envvar to be considered
must start with that prefix and will have that prefix stripped away.
For example an envvar `FUU_bar_xy` with a prefix `FUU` is mapped to a property called `bar.xy` (case-sensitive).

.Read configuration values from envvars and Java sys props
====
[source]
----
include::{src}[tag=envvarsyspropsource]
----
[source,bash]
----
include::{src}[tag=set-envvarsyspropsource]
----
====

An often used alternative is to rely on <<templating>> to read specific envvars.

// TODO: === Logical Sources

== ConfiJ's ServiceLoaders [[serviceloader]]

ConfiJ allows utilizing Java's https://docs.oracle.com/javase/8/docs/api/?java/util/ServiceLoader.html[ServiceLoader]
mechanism to register additional services like source formats or validators.
All you have to do is to add the file with the service-interface name to META-INF/services.
In this service file you list the fully qualified classnames of your constraint validator classes (one per line).

.Custom Resource Provider as ServiceLoader
====
[source]
----
include::{src}[tag=resourceprovider-service]

include::{src}[tag=resourceprovider]
----
====

To change the priority of a service loader instance implement the `ServiceLoaderPriority`.

.Custom Resource Provider as ServiceLoader with lowered priority
====
[source]
----
include::{src}[tag=resourceprovider-service-ignored]
----
====
