= Templating [[variables]]
:src: ../../test/java/ch/kk7/confij/docs/Templates.java
:resources: ../../test/resources
:home: ../../test/home

All configuration values might contain placeholders referencing other values.
Placeholders are only resolved after all sources were loaded.
Therefore it is possible for an unfinished configuration to contain undefined references.

Additionally some source paths are subject to templating (see <<anysource>>).

== built-in Templating [[templating]]

Any property can contain placeholders wrapped in `${ }`.
These referenced properties can themselves reference other properties.

.Simple Variable replacement
====
[source]
----
include::{src}[tag=simple]
----
----
given:  name=
yields: hello → Hi John

given:  name=Bob
yields: hello → Hi Bob

given:  hello=Cya
yields: hello → Cya
----
====

To disable templating support, see <<templates-custom>>.

=== Nested Properties

Variables are always relative to the node that defines them.

.Referencing nested properties
====
[source]
----
include::{src}[tag=relative-interface]
----
[source]
----
include::{src}[tag=relative]
----
====

<1> Variables can reference nested properties. Default segment separator is a dot.
    Note that the reference is still relative to where `body` is defined.

<2> To reference a property relative to the root configuration, prefix it with a dot.
    In this example `Letter` is the root.

=== Recursive Properties

Variables themselves can be built out of other variables.

.Recursive Variable replacement
====
[source]
----
include::{src}[tag=recursive]
----
====

== Custom Templating [[templates-custom]]

It is possible register a custom templating functionality globally or per property.
One use case is to disable templating per property.

.Disable templating per property using an annotation
====
[source]
----
include::{src}[tag=noop]
----
====

.Disable templating for interface and all its children
====
[source]
----
include::{src}[tag=global-noop]
----
====

.Disable templating programmatically at initialization
====
[source]
----
include::{src}[tag=builder-noop]
----
====

A custom templating engine can be registered in the same ways.
Every custom resolver must provide an empty constructor.

.Custom sample templating
====
[source]
----
include::{src}[tag=customresolver]
----
====
