= Variable Substitution [[variables]]
:src: ../../test/java/ch/kk7/confij/docs/Variables.java
:resources: ../../test/resources
:home: ../../test/home

All configuration values might contain placeholders referencing other values.
Placeholders are only resolved after all sources were loaded.
Therefore it is possible for an unfinished configuration to contain undefined references.

Additionally some source paths are subject to templating.
In these cases all references variables must already be defined.

== built-in Variable Substitution

Any property can contain placeholders wrapped in `${ }`.
These variables can reference other properties.

.Simple Variable replacement
====
[source]
----
include::{src}[tag=simple]
----
----
given:  name=
yields: hello → Hi John

given:  name=Bob
yields: hello → Hi Bob

given:  hello=Cya
yields: hello → Cya
----
====

=== Nested Variables

Variables are always relative to the node that defines them.

.Referencing nested properties
====
[source]
----
include::{src}[tag=relative-interface]
----
[source]
----
include::{src}[tag=relative]
----
====

<1> Variables can reference nested properties. Default segment separator is a dot.
    Note that the reference is still relative to where `body` is defined.

<2> To reference a property relative to the root configuration, prefix it with a dot.
    In this example `Letter` is the root.

=== Recursive Variables

Variables themselves can be built out of other variables.

.Recursive Variable replacement
====
[source]
----
include::{src}[tag=recursive]
----
====

== Noop Variable Substitution

- relative to node
- can do absolute
- can do recursive
- even allowed in source paths

TIP: To implement your own
